manifest:
  remotes:
    - name: YancyGao0910
      url-base: https://github.com/YancyGao0910
    - name: DoctorWangWang
      url-base: https://github.com/DoctorWangWang
  projects:
    - name: zmkfirmware
      remote: YancyGao0910
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: DoctorWangWang
      revision: main
      
  self:
    path: config
